// Generates ScamwatchChat/components/icons.tsx: plain inline-SVG versions of the
// Fluent System Icons the control uses (MIT, from @fluentui/react-icons).
//
// Why not import @fluentui/react-icons directly? It bundles its own copy of
// @griffel/react, which imports react/jsx-runtime — and that doesn't resolve
// against the React 16 platform library PCF provides. Inline SVGs have no
// runtime dependencies and keep the bundle small.
//
// To add an icon: add its name below, run `npm run icons`, import it from ./icons.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const ICONS = [
  "ArrowDownload16Regular",
  "ArrowSortDown16Regular",
  "ArrowSortUp16Regular",
  "ArrowSync16Regular",
  "ArrowUpload16Regular",
  "ArrowUpload20Regular",
  "Bot20Regular",
  "CheckboxChecked16Regular",
  "CheckboxUnchecked16Regular",
  "Checkmark16Regular",
  "Copy16Regular",
  "Delete16Regular",
  "Delete20Regular",
  "Dismiss16Regular",
  "Dismiss20Regular",
  "DocumentText20Regular",
  "Eye16Regular",
  "EyeOff16Regular",
  "FullScreenMaximize16Regular",
  "MoreVertical16Regular",
  "Person20Regular",
  "PersonKey20Regular",
  "Pin12Regular",
  "Pin16Regular",
  "PinOff16Regular",
  "Search16Regular",
  "Send20Filled",
  "Settings20Regular",
  "Stop16Regular",
  "Stop20Regular",
];

const require = createRequire(import.meta.url);
const root = dirname(require.resolve("@fluentui/react-icons/package.json"));
const chunkDir = join(root, "lib-cjs", "sizedIcons");
const sources = readdirSync(chunkDir)
  .filter((f) => f.endsWith(".cjs"))
  .map((f) => readFileSync(join(chunkDir, f), "utf8"));

const lines = [
  "// Generated by scripts/generate-icons.mjs from @fluentui/react-icons (MIT). Do not edit by hand.",
  'import * as React from "react";',
  "",
  "export type IconProps = React.SVGAttributes<SVGSVGElement>;",
  "",
  "function icon(name: string, size: number, paths: string[]) {",
  "  const Icon = (props: IconProps) =>",
  "    React.createElement(",
  '      "svg",',
  '      { width: "1em", height: "1em", viewBox: `0 0 ${size} ${size}`, fill: "currentColor", "aria-hidden": true, focusable: false, ...props },',
  '      paths.map((d, i) => React.createElement("path", { key: i, d })),',
  "    );",
  "  Icon.displayName = name;",
  "  return Icon;",
  "}",
  "",
];

for (const name of ICONS) {
  const pattern = new RegExp(`createFluentIcon\\('${name}', "(\\d+)", (\\[[^\\]]*\\])`);
  const match = sources.map((s) => s.match(pattern)).find(Boolean);
  if (!match) {
    throw new Error(`Icon not found: ${name}`);
  }
  lines.push(`export const ${name} = icon("${name}", ${match[1]}, ${match[2]});`);
}

const out = join(dirname(new URL(import.meta.url).pathname), "..", "ScamwatchChat", "components", "icons.tsx");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`Wrote ${ICONS.length} icons to ${out}`);
